# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
systemProp.file.encoding=utf-8

# Minecraft/Forge
minecraft_version=1.20.1
forge_version=47.4.23

# Mod properties
mod_id=dsurround
mod_version=1.2.0
maven_group=org.orecruncher

# Dependencies
cloth_version=11.1.136
nashorn_version=15.4
architectury_version=9.1.13
