package org.orecruncher.dsurround.mixins.core;

import net.minecraft.core.BlockPos;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.level.block.state.BlockState;
import org.orecruncher.dsurround.Configuration;
import org.orecruncher.dsurround.eventing.ClientEventHooks;
import org.orecruncher.dsurround.lib.config.ConfigurationData;
import org.orecruncher.dsurround.lib.GameUtils;
import org.orecruncher.dsurround.mixinutils.MixinHelpers;
import org.orecruncher.dsurround.tags.EntityEffectTags;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Unique;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

/**
 * 1.20.1: Player overrides playStepSound, so the Entity-level MixinEntity cannot
 * cancel the local player's vanilla step (double footsteps with the DS generator).
 * Cancel at Player level and re-raise the step event for brush/armor accents.
 */
@Mixin(Player.class)
public abstract class MixinPlayer {

    @Unique
    private static final double DSURROUND_MAX_ACCENT_RANGE = 16.0 * 16.0;

    @Inject(method = "playStepSound(Lnet/minecraft/core/BlockPos;Lnet/minecraft/world/level/block/state/BlockState;)V", at = @At("HEAD"), cancellable = true)
    public void dsurround_cancelPlayerStep(BlockPos pos, BlockState state, CallbackInfo ci) {
        // The local player's footsteps are generated by DS's FootstepGenerator,
        // so suppress the vanilla step sound to avoid double sounds. When the
        // footstep volume slider is at zero, let the vanilla footsteps play.
        if (((net.minecraft.world.entity.Entity)(Object) this).level().isClientSide() && ((Object) this) instanceof net.minecraft.client.player.LocalPlayer
                && ConfigurationData.getConfig(Configuration.class).soundOptions.footstepVolume > 0)
            ci.cancel();
    }

    @Inject(method = "playStepSound(Lnet/minecraft/core/BlockPos;Lnet/minecraft/world/level/block/state/BlockState;)V", at = @At("TAIL"))
    public void dsurround_playStepSound(BlockPos pos, BlockState state, CallbackInfo ci) {
        // Only want to enable eventing if accents are enabled
        if (MixinHelpers.footstepAccentsConfig.enableAccents && ((net.minecraft.world.entity.Entity)(Object) this).level().isClientSide()) {
            var self = (Entity) ((Object) this);

            // Is the entity in range? If not, avoid generating an event
            if (GameUtils.getPlayer().orElseThrow().distanceToSqr(self) > DSURROUND_MAX_ACCENT_RANGE)
                return;

            // Lastly, the entity has to be tagged
            if (MixinHelpers.TAG_LIBRARY.is(EntityEffectTags.BRUSH_STEP, self.getType())) {
                ClientEventHooks.ENTITY_STEP_EVENT.raise().onStep(self, pos, state);
            }
        }
    }
}
