package org.orecruncher.dsurround.mixins.core;

import net.minecraft.core.BlockPos;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.level.block.state.BlockState;
import org.orecruncher.dsurround.eventing.ClientEventHooks;
import org.orecruncher.dsurround.lib.GameUtils;
import org.orecruncher.dsurround.mixinutils.MixinHelpers;
import org.orecruncher.dsurround.processing.FootstepGenerator;
import org.orecruncher.dsurround.tags.EntityEffectTags;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Unique;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

/**
 * 1.20.1: Player overrides playStepSound, so the Entity-level MixinEntity cannot
 * cancel the local player's vanilla step (double footsteps with the DS generator).
 * Cancel at Player level and re-raise the step event for brush/armor accents.
 */
@Mixin(Player.class)
public abstract class MixinPlayer {

    @Unique
    private static final double DSURROUND_MAX_ACCENT_RANGE = 16.0 * 16.0;

    @Inject(method = "playStepSound(Lnet/minecraft/core/BlockPos;Lnet/minecraft/world/level/block/state/BlockState;)V", at = @At("HEAD"), cancellable = true)
    public void dsurround_cancelPlayerStep(BlockPos pos, BlockState state, CallbackInfo ci) {
        // The local player's footsteps are generated by DS's FootstepGenerator, so
        // suppress the vanilla step sound to avoid double sounds. The gate is shared
        // with the generator (single source of truth): it is false whenever the
        // footstep system is switched off in the config OR the volume slider is at
        // zero, so the vanilla footsteps always come back instead of the player
        // falling silent. Do not test the volume alone here - this HEAD cancels the
        // whole Player.playStepSound body, so the Entity-level mixin never gets a say.
        if (((net.minecraft.world.entity.Entity)(Object) this).level().isClientSide() && ((Object) this) instanceof net.minecraft.client.player.LocalPlayer
                && FootstepGenerator.shouldSuppressVanillaStep())
            ci.cancel();
    }

    @Inject(method = "playStepSound(Lnet/minecraft/core/BlockPos;Lnet/minecraft/world/level/block/state/BlockState;)V", at = @At("TAIL"))
    public void dsurround_playStepSound(BlockPos pos, BlockState state, CallbackInfo ci) {
        // Only want to enable eventing if accents are enabled
        if (MixinHelpers.footstepAccentsConfig.enableAccents && ((net.minecraft.world.entity.Entity)(Object) this).level().isClientSide()) {
            var self = (Entity) ((Object) this);

            // Is the entity in range? If not, avoid generating an event. getPlayer() is empty for
            // the ticks where the client level exists but the local player does not (the disconnect
            // and respawn windows), and this runs from a TAIL injector inside the entity tick, so
            // it must bail out rather than throw into the client tick loop.
            var player = GameUtils.getPlayer();
            if (player.isEmpty() || player.get().distanceToSqr(self) > DSURROUND_MAX_ACCENT_RANGE)
                return;

            // Lastly, the entity has to be tagged
            if (MixinHelpers.TAG_LIBRARY.is(EntityEffectTags.BRUSH_STEP, self.getType())) {
                ClientEventHooks.ENTITY_STEP_EVENT.raise().onStep(self, pos, state);
            }
        }
    }
}
