license="${mod_license}"
issueTrackerURL="${mod_issues_url}"
displayURL="${mod_homepage_url}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_author}"
description='''
${mod_description}
'''
logoFile="assets/dsurround/icon.png"

[[mixins]]
config="dsurround.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="architectury"
type="required"
versionRange="[13.0.8,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="cloth_config"
type="required"
versionRange="[${clothapi_version},)"
ordering="AFTER"
side="CLIENT"
